name: frappe_mobile_custom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.0
  connectivity_plus: ^3.0.4
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.2.3
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.1.0
  flutter_typeahead: ^3.1.0
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  intl: ^0.17.0
  get: 4.6.5
  get_storage: ^2.1.1
  flutter_svg: ^0.22.0
  timeago: ^3.0.2
  flutter_mentions: ^2.0.1
  pull_to_refresh: ^2.0.0
  dio_http_cache: ^0.3.0
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  awesome_dialog: ^3.0.2
  persistent_bottom_nav_bar: ^5.0.2
  lazy_load_indexed_stack: ^0.1.4
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+4
  photo_view: ^0.14.0
  timelines: ^0.1.0
  flutter_html: ^2.0.0

  flutter: 
    sdk: flutter
  flutter_map: ^3.1.0



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter



flutter: 
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
